import type { Question } from "@/types/questionnaire";

export const QUESTIONNAIRE_DEMO_QUESTIONS: Question[] = [
  {
    id: "demo-single",
    key: "demo-single",
    prompt: "How would you honestly rate yourself in your primary skill?",
    helperText:
      "Claimed level. Compared against validated level after Skill Evaluation.",
    inputType: "single",
    required: true,
    options: ["Entry", "Junior", "Mid", "Senior", "Expert"],
  },
  {
    id: "demo-multi",
    key: "demo-multi",
    prompt: "Which tools or platforms do you use regularly?",
    helperText: "Select all technologies you work with.",
    inputType: "multi",
    required: false,
    options: [
      "React",
      "Next.js",
      "Vue.js",
      "Angular",
      "Svelte",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "Express",
      "Python",
      "Django",
      "Flask",
      "Other",
    ],
    conditional: { trigger_option: "Other", reveals: "free_text_input" },
  },
  {
    id: "demo-text",
    key: "demo-text",
    prompt:
      "Describe a situation where you had to make a difficult decision that affected others at work.",
    helperText: "Used by AI as leadership context for assessment framing.",
    inputType: "text_required",
    required: true,
  },

  // --------------------- //
  // -------------------- //

  {
    id: "a41f5f94-a35d-41e8-a32c-6095f9791845",
    key: "job_title",
    sourceQuestionNumber: 1,
    sourceSection: 1,
    inputType: "text_required",
    required: true,
    minLength: 2,
    prompt: "Job Title",
    helperText: null,
  },
  {
    id: "8900e03e-3251-41ce-be13-318ba1f3b0ae",
    key: "years_experience",
    sourceQuestionNumber: 2,
    sourceSection: 1,
    inputType: "single",
    required: true,
    prompt: "Years Experience",
    helperText: null,
    options: ["0_1_yr", "1_3_yrs", "3_5_yrs", "5_10_yrs", "10_plus_yrs"],
  },
  {
    id: "a92cd720-d1e6-4024-9fd7-7fd74ed7ef13",
    key: "industries",
    sourceQuestionNumber: 3,
    sourceSection: 1,
    inputType: "multi",
    required: true,
    prompt: "Industries",
    helperText: null,
    options: [
      "fintech",
      "healthcare",
      "ecommerce",
      "government",
      "ngo",
      "media_entertainment",
      "education",
      "logistics",
      "telecoms",
      "oil_gas",
      "agriculture",
      "other",
    ],
    otherTextKey: "industries_other",
  },
  {
    id: "71627416-6ab1-4680-ba22-cae8cc0a8928",
    key: "specialization",
    sourceQuestionNumber: 12,
    sourceSection: 2,
    inputType: "single",
    required: true,
    prompt: "Specialization",
    helperText: null,
    options: [
      "frontend",
      "backend",
      "full_stack",
      "mobile",
      "embedded",
      "other",
    ],
  },
  {
    id: "81e53942-2bd8-4f6e-a699-66060382a622",
    key: "tools",
    sourceQuestionNumber: 14,
    sourceSection: 2,
    inputType: "multi",
    required: false,
    prompt: "Tools",
    helperText: null,
    options: [
      "git",
      "github",
      "vscode",
      "react",
      "node",
      "python",
      "docker",
      "aws",
      "other",
    ],
    otherTextKey: "tools_other",
  },
  {
    id: "00b3b577-4053-40fb-8cd4-1499b818beab",
    key: "primary_tool_duration",
    sourceQuestionNumber: 15,
    sourceSection: 2,
    inputType: "single",
    required: true,
    prompt: "Primary Tool Duration",
    helperText: null,
    options: [
      "less_than_6_months",
      "6_12_months",
      "1_2_years",
      "3_5_years",
      "5_plus_years",
    ],
  },
  {
    id: "f5969e4b-98c9-4704-a97b-0f279800ffa9",
    key: "shipped_deliverable",
    sourceQuestionNumber: 17,
    sourceSection: 2,
    inputType: "single",
    required: true,
    prompt: "Shipped Deliverable",
    helperText: null,
    options: ["yes_multiple", "yes_once", "not_yet"],
  },
  {
    id: "01fe2086-0a83-4eb3-813f-1b0821093326",
    key: "managed_team",
    sourceQuestionNumber: 19,
    sourceSection: 3,
    inputType: "single",
    required: true,
    prompt: "Managed Team",
    helperText: null,
    options: ["no", "yes_1_to_3", "yes_4_to_10", "yes_10_plus"],
  },
];
