type TermsOfUse = {
  title: string;
  paragraph: string;
  list?: string[];
};
const termsOfUseData: TermsOfUse[] = [
  {
    title: "Acceptance of terms",
    paragraph:
      "By accessing or using CredLane — as a candidate, employer, or visitor — you agree to be bound by these Terms of Use. If you do not agree, you must not use the platform.",
  },
  {
    title: "Who can use CredLane",
    paragraph:
      "CredLane is available to individuals who meet the following requirements:",
    list: [
      "You are at least 18 years of age",
      "are an early-career professional, bootcamp participant, or an employer hiring African talent",
      "You are registering with your own accurate information — not on behalf of someone else",
      "You have not previously been removed from CredLane for a terms violation",
    ],
  },
  {
    title: "Candidate obligations",
    paragraph:
      "As a candidate, you agree to use the platform honestly. Your conduct reflects the standards CredLane is built on.",
    list: [
      "Provide accurate, truthful information during registration and profile setup",
      "Complete all assessments independently, without external help or AI tools unless stated",
      "Not share assessment questions or answers with anyone",
      "Not misrepresent your identity, qualifications, or location",
    ],
  },
  {
    title: "Assessment integrity",
    paragraph:
      "The platform monitors all assessment sessions. The following rules apply at all times:",
    list: [
      "No external assistance — AI tools, other people, or reference material are not permitted",
      "No tab switching — three or more violations trigger automatic submission",
      "No copy/paste — disabled at the platform level during technical assessments",
      "Each retake uses a different question set — sharing questions from a previous attempt is a breach",
    ],
  },
  {
    title: "Verified profiles and scores",
    paragraph:
      "Scores are generated by CredLane and represent an objective record of performance at the time of assessment.",
    list: [
      "Verified scores are owned by CredLane and cannot be edited by the candidate",
      "Profiles are only published once a candidate reaches Job Ready (composite score of 75 or above)",
      "Candidates may share their profile link but may not alter the underlying data",
      "CredLane may revoke a verified profile if evidence of fraud is identified",
    ],
  },
  {
    title: "Employer obligations",
    paragraph:
      "Employers using the discovery dashboard agree to use candidate data responsibly and fairly.",
    list: [
      "Use candidate data only for evaluating and hiring talent",
      "Not share or resell candidate data outside your organisation without written consent",
      "Not contact candidates through channels outside CredLane without first initiating contact on the platform",
      "Comply with all applicable anti-discrimination laws when reviewing and shortlisting",
    ],
  },
  {
    title: "Intellectual property",
    paragraph:
      "All content, assessments, and materials on CredLane are the property of CredLane or its licensors and are protected by applicable intellectual property laws.",
    list: [
      "You may not reproduce or distribute any part of the platform without written permission",
      "Assessment questions and task briefs are confidential and may not be shared",
      "The CredLane name and verified badge may only be used as specified by CredLane",
    ],
  },
  {
    title: "Limitation of liability",
    paragraph:
      "CredLane provides a verified evaluation and discovery service. We do not guarantee employment outcomes.",
    list: [
      "CredLane is not liable for any hiring decisions made by employers based on verified profiles",
      "We do not guarantee that Job Ready candidates will receive job offers or employer contact",
      "Our total liability to any user shall not exceed the amount paid by that user in the preceding 12 months",
    ],
  },
  {
    title: "Termination",
    paragraph:
      "We may suspend or permanently terminate any account that violates these terms or undermines platform integrity.",
    list: [
      "Termination may occur with or without prior notice depending on the severity of the breach",
      "Your profile will be unpublished and access removed upon termination",
      "You may request account deletion at any time — data deletion follows our Privacy Policy",
      "Accounts terminated for fraud are permanently ineligible for reinstatement",
    ],
  },
  {
    title: "Governing law",
    paragraph:
      "These terms are governed by the laws of the Federal Republic of Nigeria. " +
      "Disputes arising from your use of CredLane are subject to the exclusive " +
      "jurisdiction of Nigerian courts, unless otherwise required by local law in " +
      "your jurisdiction.",
  },
  {
    title: "Changes to these terms",
    paragraph:
      "We may update these terms from time to time. We will notify you of any material changes by posting a new version on this page.",
    list: [
      "A notice will be posted on the platform and sent to your registered email",
      "Continued use after the effective date constitutes acceptance of the updated terms",
    ],
  },
];

/** Derived from the section data so the nav can never drift from the headings. */
const termsOfUseNav = termsOfUseData.map((section) => section.title);

export { termsOfUseData, termsOfUseNav };
export type { TermsOfUse };
